#pragma once
#include "ReferenceCount.hpp"

class AbstractEvaluationResultImpl;
class AbstractEvaluatorImpl;
class AnalysisResultImpl;
class ArmImpl;
class AssignmentMapImpl;
class BacklogDbImpl;
class BacklogImpl;
class BlockPermutationEvaluatorImpl;
class BlockPermutationEvaluationResultImpl;
class BrokerImpl;
class CodeBrokerImpl;
class ConditionImpl;
class DFGAddImpl;
class DFGAndImpl;
class DFGCallImpl;
class DFGCarryImpl;
class DFGConstantImpl;
class DFGDisplayImpl;
class DFGLoadImpl;
class DFGMultImpl;
class DFGNodeImpl;
class DFGOpaqueImpl;
class DFGOrImpl;
class DFGOverflowImpl;
class DFGraphImpl;
class DFGRegisterImpl;
class DFGRotateImpl;
class DFGShiftImpl;
class DFGStoreImpl;
class DFGXorImpl;
class EmptyAnalysisResultImpl;
class OpaqueAssignmentImpl;
class PathOracleImpl;
class PredicateImpl;
class ProcessorImpl;
class SignatureDefinitionImpl;
class SignatureBrokerImpl;
class SignatureParserImpl;
class SignatureEvaluationResultImpl;
class SignatureEvaluatorImpl;
class SparseMatrixImpl;
class ThreadPoolImpl;
class ThreadTaskImpl;
class ThreadTaskResultImpl;

typedef rfc_ptr<AbstractEvaluationResultImpl> AbstractEvaluationResult;
typedef rfc_ptr<AbstractEvaluatorImpl> AbstractEvaluator;
typedef rfc_ptr<AnalysisResultImpl> AnalysisResult;
typedef rfc_ptr<ArmImpl> Arm;
typedef rfc_ptr<AssignmentMapImpl> AssignmentMap;
typedef rfc_ptr<BacklogDbImpl> BacklogDb;
typedef rfc_ptr<BacklogImpl> Backlog;
typedef rfc_ptr<BlockPermutationEvaluatorImpl> BlockPermutationEvaluator;
typedef rfc_ptr<BlockPermutationEvaluationResultImpl> BlockPermutationEvaluationResult;
typedef rfc_ptr<BrokerImpl> Broker;
typedef rfc_ptr<CodeBrokerImpl> CodeBroker;
typedef rfc_ptr<ConditionImpl> Condition;
typedef rfc_ptr<DFGAddImpl> DFGAdd;
typedef rfc_ptr<DFGAndImpl> DFGAnd;
typedef rfc_ptr<DFGCallImpl> DFGCall;
typedef rfc_ptr<DFGCarryImpl> DFGCarry;
typedef rfc_ptr<DFGConstantImpl> DFGConstant;
typedef rfc_ptr<DFGDisplayImpl> DFGDisplay;
typedef rfc_ptr<DFGLoadImpl> DFGLoad;
typedef rfc_ptr<DFGMultImpl> DFGMult;
typedef rfc_ptr<DFGNodeImpl> DFGNode;
typedef rfc_ptr<DFGOpaqueImpl> DFGOpaque;
typedef rfc_ptr<DFGOrImpl> DFGOr;
typedef rfc_ptr<DFGOverflowImpl> DFGOverflow;
typedef rfc_ptr<DFGraphImpl> DFGraph;
typedef rfc_ptr<DFGRegisterImpl> DFGRegister;
typedef rfc_ptr<DFGRotateImpl> DFGRotate;
typedef rfc_ptr<DFGShiftImpl> DFGShift;
typedef rfc_ptr<DFGStoreImpl> DFGStore;
typedef rfc_ptr<DFGXorImpl> DFGXor;
typedef rfc_ptr<EmptyAnalysisResultImpl> EmptyAnalysisResult;
typedef rfc_ptr<OpaqueAssignmentImpl> OpaqueAssignment;
typedef rfc_ptr<PathOracleImpl> PathOracle;
typedef rfc_ptr<PredicateImpl> Predicate;
typedef rfc_ptr<ProcessorImpl> Processor;
typedef rfc_ptr<SignatureDefinitionImpl> SignatureDefinition;
typedef rfc_ptr<SignatureBrokerImpl> SignatureBroker;
typedef rfc_ptr<SignatureParserImpl> SignatureParser;
typedef rfc_ptr<SignatureEvaluationResultImpl> SignatureEvaluationResult;
typedef rfc_ptr<SignatureEvaluatorImpl> SignatureEvaluator;
typedef rfc_ptr<SparseMatrixImpl> SparseMatrix;
typedef rfc_ptr<ThreadPoolImpl> ThreadPool;
typedef rfc_ptr<ThreadTaskImpl> ThreadTask;
typedef rfc_ptr<ThreadTaskResultImpl> ThreadTaskResult;
